
-- Create role and schema for ajaykishan
CREATE ROLE student_ajaykishan_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_AJAYKISHAN;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_ajaykishan_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_AJAYKISHAN TO ROLE student_ajaykishan_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_AJAYKISHAN TO ROLE student_ajaykishan_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_AJAYKISHAN TO ROLE student_ajaykishan_role;

-- Create user
CREATE USER ajaykishan_user
  PASSWORD = 'ajaykishan1234!'
  DEFAULT_ROLE = student_ajaykishan_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_ajaykishan_role TO USER ajaykishan_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_ajaykishan_role;


-- Create role and schema for alyssa
CREATE ROLE student_alyssa_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_ALYSSA;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_alyssa_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_ALYSSA TO ROLE student_alyssa_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_ALYSSA TO ROLE student_alyssa_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_ALYSSA TO ROLE student_alyssa_role;

-- Create user
CREATE USER alyssa_user
  PASSWORD = 'alyssa1234!'
  DEFAULT_ROLE = student_alyssa_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_alyssa_role TO USER alyssa_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_alyssa_role;


-- Create role and schema for chen
CREATE ROLE student_chen_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_CHEN;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_chen_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_CHEN TO ROLE student_chen_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_CHEN TO ROLE student_chen_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_CHEN TO ROLE student_chen_role;

-- Create user
CREATE USER chen_user
  PASSWORD = 'chen1234!'
  DEFAULT_ROLE = student_chen_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_chen_role TO USER chen_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_chen_role;


-- Create role and schema for daniel
CREATE ROLE student_daniel_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_DANIEL;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_daniel_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

-- Create user
CREATE USER daniel_user
  PASSWORD = 'daniel1234!'
  DEFAULT_ROLE = student_daniel_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_daniel_role TO USER daniel_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_daniel_role;


-- Create role and schema for daniel
CREATE ROLE student_daniel_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_DANIEL;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_daniel_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_DANIEL TO ROLE student_daniel_role;

-- Create user
CREATE USER daniel_user
  PASSWORD = 'daniel1234!'
  DEFAULT_ROLE = student_daniel_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_daniel_role TO USER daniel_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_daniel_role;


-- Create role and schema for gayathri
CREATE ROLE student_gayathri_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_GAYATHRI;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_gayathri_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_GAYATHRI TO ROLE student_gayathri_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_GAYATHRI TO ROLE student_gayathri_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_GAYATHRI TO ROLE student_gayathri_role;

-- Create user
CREATE USER gayathri_user
  PASSWORD = 'gayathri1234!'
  DEFAULT_ROLE = student_gayathri_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_gayathri_role TO USER gayathri_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_gayathri_role;


-- Create role and schema for hemant
CREATE ROLE student_hemant_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_HEMANT;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_hemant_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_HEMANT TO ROLE student_hemant_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_HEMANT TO ROLE student_hemant_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_HEMANT TO ROLE student_hemant_role;

-- Create user
CREATE USER hemant_user
  PASSWORD = 'hemant1234!'
  DEFAULT_ROLE = student_hemant_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_hemant_role TO USER hemant_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_hemant_role;


-- Create role and schema for hoang
CREATE ROLE student_hoang_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_HOANG;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_hoang_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_HOANG TO ROLE student_hoang_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_HOANG TO ROLE student_hoang_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_HOANG TO ROLE student_hoang_role;

-- Create user
CREATE USER hoang_user
  PASSWORD = 'hoang1234!'
  DEFAULT_ROLE = student_hoang_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_hoang_role TO USER hoang_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_hoang_role;


-- Create role and schema for james
CREATE ROLE student_james_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_JAMES;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_james_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_JAMES TO ROLE student_james_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_JAMES TO ROLE student_james_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_JAMES TO ROLE student_james_role;

-- Create user
CREATE USER james_user
  PASSWORD = 'james1234!'
  DEFAULT_ROLE = student_james_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_james_role TO USER james_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_james_role;


-- Create role and schema for john
CREATE ROLE student_john_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_JOHN;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_john_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_JOHN TO ROLE student_john_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_JOHN TO ROLE student_john_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_JOHN TO ROLE student_john_role;

-- Create user
CREATE USER john_user
  PASSWORD = 'john1234!'
  DEFAULT_ROLE = student_john_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_john_role TO USER john_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_john_role;


-- Create role and schema for jon
CREATE ROLE student_jon_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_JON;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_jon_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_JON TO ROLE student_jon_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_JON TO ROLE student_jon_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_JON TO ROLE student_jon_role;

-- Create user
CREATE USER jon_user
  PASSWORD = 'jon1234!'
  DEFAULT_ROLE = student_jon_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_jon_role TO USER jon_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_jon_role;


-- Create role and schema for jonathan
CREATE ROLE student_jonathan_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_JONATHAN;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_jonathan_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_JONATHAN TO ROLE student_jonathan_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_JONATHAN TO ROLE student_jonathan_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_JONATHAN TO ROLE student_jonathan_role;

-- Create user
CREATE USER jonathan_user
  PASSWORD = 'jonathan1234!'
  DEFAULT_ROLE = student_jonathan_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_jonathan_role TO USER jonathan_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_jonathan_role;


-- Create role and schema for julie
CREATE ROLE student_julie_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_JULIE;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_julie_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_JULIE TO ROLE student_julie_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_JULIE TO ROLE student_julie_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_JULIE TO ROLE student_julie_role;

-- Create user
CREATE USER julie_user
  PASSWORD = 'julie1234!'
  DEFAULT_ROLE = student_julie_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_julie_role TO USER julie_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_julie_role;


-- Create role and schema for michael
CREATE ROLE student_michael_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_MICHAEL;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_michael_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_MICHAEL TO ROLE student_michael_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_MICHAEL TO ROLE student_michael_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_MICHAEL TO ROLE student_michael_role;

-- Create user
CREATE USER michael_user
  PASSWORD = 'michael1234!'
  DEFAULT_ROLE = student_michael_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_michael_role TO USER michael_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_michael_role;


-- Create role and schema for mounika
CREATE ROLE student_mounika_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_MOUNIKA;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_mounika_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_MOUNIKA TO ROLE student_mounika_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_MOUNIKA TO ROLE student_mounika_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_MOUNIKA TO ROLE student_mounika_role;

-- Create user
CREATE USER mounika_user
  PASSWORD = 'mounika1234!'
  DEFAULT_ROLE = student_mounika_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_mounika_role TO USER mounika_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_mounika_role;


-- Create role and schema for paran
CREATE ROLE student_paran_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_PARAN;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_paran_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_PARAN TO ROLE student_paran_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_PARAN TO ROLE student_paran_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_PARAN TO ROLE student_paran_role;

-- Create user
CREATE USER paran_user
  PASSWORD = 'paran1234!'
  DEFAULT_ROLE = student_paran_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_paran_role TO USER paran_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_paran_role;


-- Create role and schema for ross
CREATE ROLE student_ross_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_ROSS;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_ross_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_ROSS TO ROLE student_ross_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_ROSS TO ROLE student_ross_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_ROSS TO ROLE student_ross_role;

-- Create user
CREATE USER ross_user
  PASSWORD = 'ross1234!'
  DEFAULT_ROLE = student_ross_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_ross_role TO USER ross_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_ross_role;


-- Create role and schema for sainath
CREATE ROLE student_sainath_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_SAINATH;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_sainath_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_SAINATH TO ROLE student_sainath_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_SAINATH TO ROLE student_sainath_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_SAINATH TO ROLE student_sainath_role;

-- Create user
CREATE USER sainath_user
  PASSWORD = 'sainath1234!'
  DEFAULT_ROLE = student_sainath_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_sainath_role TO USER sainath_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_sainath_role;


-- Create role and schema for santhosh
CREATE ROLE student_santhosh_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_SANTHOSH;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_santhosh_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_SANTHOSH TO ROLE student_santhosh_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_SANTHOSH TO ROLE student_santhosh_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_SANTHOSH TO ROLE student_santhosh_role;

-- Create user
CREATE USER santhosh_user
  PASSWORD = 'santhosh1234!'
  DEFAULT_ROLE = student_santhosh_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_santhosh_role TO USER santhosh_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_santhosh_role;


-- Create role and schema for scott
CREATE ROLE student_scott_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_SCOTT;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_scott_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_SCOTT TO ROLE student_scott_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_SCOTT TO ROLE student_scott_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_SCOTT TO ROLE student_scott_role;

-- Create user
CREATE USER scott_user
  PASSWORD = 'scott1234!'
  DEFAULT_ROLE = student_scott_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_scott_role TO USER scott_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_scott_role;


-- Create role and schema for victor
CREATE ROLE student_victor_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_VICTOR;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_victor_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_VICTOR TO ROLE student_victor_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_VICTOR TO ROLE student_victor_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_VICTOR TO ROLE student_victor_role;

-- Create user
CREATE USER victor_user
  PASSWORD = 'victor1234!'
  DEFAULT_ROLE = student_victor_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_victor_role TO USER victor_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_victor_role;


-- Create role and schema for enzo
CREATE ROLE student_enzo_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_ENZO;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_enzo_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_ENZO TO ROLE student_enzo_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_ENZO TO ROLE student_enzo_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_ENZO TO ROLE student_enzo_role;

-- Create user
CREATE USER enzo_user
  PASSWORD = 'enzo1234!'
  DEFAULT_ROLE = student_enzo_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_enzo_role TO USER enzo_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_enzo_role;


-- Create role and schema for reggie
CREATE ROLE student_reggie_role;

CREATE SCHEMA IF NOT EXISTS DBT_DEMO_05042026.STUDENT_REGGIE;

GRANT USAGE ON DATABASE DBT_DEMO_05042026 TO ROLE student_reggie_role;
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STUDENT_REGGIE TO ROLE student_reggie_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT 
  ON SCHEMA DBT_DEMO_05042026.STUDENT_REGGIE TO ROLE student_reggie_role;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
  ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STUDENT_REGGIE TO ROLE student_reggie_role;

-- Create user
CREATE USER reggie_user
  PASSWORD = 'reggie1234!'
  DEFAULT_ROLE = student_reggie_role
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE student_reggie_role TO USER reggie_user;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE student_reggie_role;
