
-- Read access to PAGILA schema for student_ajaykishan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ajaykishan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ajaykishan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ajaykishan_role;


-- Read access to PUBLIC schema for student_ajaykishan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ajaykishan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ajaykishan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ajaykishan_role;


-- Read access to STG schema for student_ajaykishan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ajaykishan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ajaykishan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ajaykishan_role;


-- Read access to PAGILA schema for student_alyssa_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_alyssa_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_alyssa_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_alyssa_role;


-- Read access to PUBLIC schema for student_alyssa_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_alyssa_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_alyssa_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_alyssa_role;


-- Read access to STG schema for student_alyssa_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_alyssa_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_alyssa_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_alyssa_role;


-- Read access to PAGILA schema for student_chen_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_chen_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_chen_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_chen_role;


-- Read access to PUBLIC schema for student_chen_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_chen_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_chen_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_chen_role;


-- Read access to STG schema for student_chen_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_chen_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_chen_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_chen_role;


-- Read access to PAGILA schema for student_daniely_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_daniely_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_daniely_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_daniely_role;


-- Read access to PUBLIC schema for student_daniely_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_daniely_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_daniely_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_daniely_role;


-- Read access to STG schema for student_daniely_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_daniely_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_daniely_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_daniely_role;


-- Read access to PAGILA schema for student_danielz_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_danielz_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_danielz_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_danielz_role;


-- Read access to PUBLIC schema for student_danielz_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_danielz_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_danielz_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_danielz_role;


-- Read access to STG schema for student_danielz_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_danielz_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_danielz_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_danielz_role;


-- Read access to PAGILA schema for student_gayathri_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_gayathri_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_gayathri_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_gayathri_role;


-- Read access to PUBLIC schema for student_gayathri_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_gayathri_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_gayathri_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_gayathri_role;


-- Read access to STG schema for student_gayathri_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_gayathri_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_gayathri_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_gayathri_role;


-- Read access to PAGILA schema for student_hemant_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hemant_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hemant_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hemant_role;


-- Read access to PUBLIC schema for student_hemant_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hemant_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hemant_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hemant_role;


-- Read access to STG schema for student_hemant_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hemant_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hemant_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hemant_role;


-- Read access to PAGILA schema for student_hoang_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hoang_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hoang_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_hoang_role;


-- Read access to PUBLIC schema for student_hoang_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hoang_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hoang_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_hoang_role;


-- Read access to STG schema for student_hoang_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hoang_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hoang_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_hoang_role;


-- Read access to PAGILA schema for student_james_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_james_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_james_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_james_role;


-- Read access to PUBLIC schema for student_james_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_james_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_james_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_james_role;


-- Read access to STG schema for student_james_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_james_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_james_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_james_role;


-- Read access to PAGILA schema for student_john_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_john_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_john_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_john_role;


-- Read access to PUBLIC schema for student_john_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_john_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_john_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_john_role;


-- Read access to STG schema for student_john_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_john_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_john_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_john_role;


-- Read access to PAGILA schema for student_jon_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jon_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jon_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jon_role;


-- Read access to PUBLIC schema for student_jon_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jon_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jon_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jon_role;


-- Read access to STG schema for student_jon_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jon_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jon_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jon_role;


-- Read access to PAGILA schema for student_jonathan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jonathan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jonathan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_jonathan_role;


-- Read access to PUBLIC schema for student_jonathan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jonathan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jonathan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_jonathan_role;


-- Read access to STG schema for student_jonathan_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jonathan_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jonathan_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_jonathan_role;


-- Read access to PAGILA schema for student_julie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_julie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_julie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_julie_role;


-- Read access to PUBLIC schema for student_julie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_julie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_julie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_julie_role;


-- Read access to STG schema for student_julie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_julie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_julie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_julie_role;


-- Read access to PAGILA schema for student_michael_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_michael_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_michael_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_michael_role;


-- Read access to PUBLIC schema for student_michael_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_michael_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_michael_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_michael_role;


-- Read access to STG schema for student_michael_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_michael_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_michael_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_michael_role;


-- Read access to PAGILA schema for student_mounika_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_mounika_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_mounika_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_mounika_role;


-- Read access to PUBLIC schema for student_mounika_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_mounika_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_mounika_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_mounika_role;


-- Read access to STG schema for student_mounika_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_mounika_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_mounika_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_mounika_role;


-- Read access to PAGILA schema for student_paran_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_paran_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_paran_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_paran_role;


-- Read access to PUBLIC schema for student_paran_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_paran_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_paran_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_paran_role;


-- Read access to STG schema for student_paran_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_paran_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_paran_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_paran_role;


-- Read access to PAGILA schema for student_ross_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ross_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ross_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_ross_role;


-- Read access to PUBLIC schema for student_ross_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ross_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ross_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_ross_role;


-- Read access to STG schema for student_ross_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ross_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ross_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_ross_role;


-- Read access to PAGILA schema for student_sainath_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_sainath_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_sainath_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_sainath_role;


-- Read access to PUBLIC schema for student_sainath_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_sainath_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_sainath_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_sainath_role;


-- Read access to STG schema for student_sainath_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_sainath_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_sainath_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_sainath_role;


-- Read access to PAGILA schema for student_santhosh_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_santhosh_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_santhosh_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_santhosh_role;


-- Read access to PUBLIC schema for student_santhosh_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_santhosh_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_santhosh_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_santhosh_role;


-- Read access to STG schema for student_santhosh_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_santhosh_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_santhosh_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_santhosh_role;


-- Read access to PAGILA schema for student_scott_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_scott_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_scott_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_scott_role;


-- Read access to PUBLIC schema for student_scott_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_scott_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_scott_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_scott_role;


-- Read access to STG schema for student_scott_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_scott_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_scott_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_scott_role;


-- Read access to PAGILA schema for student_victor_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_victor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_victor_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_victor_role;


-- Read access to PUBLIC schema for student_victor_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_victor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_victor_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_victor_role;


-- Read access to STG schema for student_victor_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_victor_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_victor_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_victor_role;


-- Read access to PAGILA schema for student_enzo_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_enzo_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_enzo_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_enzo_role;


-- Read access to PUBLIC schema for student_enzo_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_enzo_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_enzo_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_enzo_role;


-- Read access to STG schema for student_enzo_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_enzo_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_enzo_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_enzo_role;


-- Read access to PAGILA schema for student_reggie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_reggie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_reggie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PAGILA TO ROLE student_reggie_role;


-- Read access to PUBLIC schema for student_reggie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_reggie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_reggie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.PUBLIC TO ROLE student_reggie_role;


-- Read access to STG schema for student_reggie_role
GRANT USAGE ON SCHEMA DBT_DEMO_05042026.STG TO ROLE student_reggie_role;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_reggie_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DEMO_05042026.STG TO ROLE student_reggie_role;
